### PR TITLE
US038 Add a linter

### PR DESCRIPTION
**Pull request by OdhranHague**
Changed linters from superlinter to eslint

- Linter failing
Screenshot 2023-12-12 at 12 10 30

- Linter passing after changes
Screenshot 2023-12-12 at 12 13 24

### CODE REVIEW

**Comment by jkelso662** [comment]
Please add both me and Joanne as approvers and one of us will do the code review :)

**Comment by jkelso662** [comment]
Jo hasn't reviewed this yet, and there is also things in here not to do with linting. I assume these will disappear when you get more into main?

**Comment by OdhranHague** [comment]
I think some of them changes came from when I merged a different branch onto this one to check for conflicts so it should all still get pushed to main. Also from now on going to use ready-for-signoff instead

**Review by lullabelle — CHANGES_REQUESTED** [review]
Hi
Team member needs to review this before Josh or I can sign off

**Review by lullabelle — APPROVED** [review]

**Pull request merged**
