### PR TITLE
US001 - View Job Roles

### PR DESCRIPTION
**Pull request by OdhranHague**
As a Kainos employee

I want to view job roles within Kainos
So that I can see all the job roles available in Kainos

Acceptance Criteria:

Can view a list of job roles within Kainos

Notes:
Job Roles table
API endpoint GET /job-roles
UI page to display results from API

Added a UI page to display job roles 
Get request to "api/job-roles" added to retrieve job roles from database

Screenshot 2023-12-06 at 10 13 04

### CODE REVIEW

**Review by Joseph-Magee — APPROVED** [review]
looks good

**Review by jkelso662 — APPROVED** [review]
The new UI bit looks good from a code review perspective. 

I'm seeing lots of duplication tho. I think this is because I approved content in another branch that is waiting to be signed off. When that first boilerplate branch gets merged, you will need to update this one with the latest from main before it can merge into main. 

To avoid this, consider using a `development` branch whereby you merge all features into it once code reviewed and tested. Everyone can branch off it for access to that content, but only merge that into main when you get customer sign-off. Just a thought! Can chat more about this at standup :)

**Review by Joseph-Magee — COMMENTED** [review]
looks good

**Comment by lullabelle** [comment]
image
can someone on the team review this first?

**Pull request merged**
